### ISSUE TITLE
connectivity matrix

### ISSUE THREAD

**Issue by 7beggars** [grahamfindlay/graphiit#2]
For now, I don't know how to declare a connectivity matrix using Graphiit. This would be in the IIT paper as described below:

```
cm = np.array ([
[0,1,1],
[1.0.1],
[1,1,0],
])
network = pyphi.Network (tpm, cm = cm, node_labels = ['A', 'B', 'C'])
```

in `graph.py `I have:

```
def pyphi_network(self):
        """Yield a PyPhi network corresponding to the graph. PyPhi node indices
           will match graph node indices."""
        return pyphi.Network(self.tpm, self.connectivity_matrix,
                             node_labels=self.node_tokens)
```

this should work when i do:

`network = pyphi.Network(tpm, cm=cm, node_labels=['A','B','C'])`

but when I run the above statement I get the error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: pyphi_network() got an unexpected keyword argument 'cm'
```

**Comment by matteograsso** [comment]
Hi Yaacov, you can create a network either by providing a tpm (and optionally a cm) to the pyphi.Network() function, or by specifying the nodes and feeding them to graphiit.

If you do the former, you have to specify a tpm. Are you giving a tpm to the pyphi.Network() function? I see you only defined a cm.

If you do the latter, you do not need a tpm or a cm, but only a list of nodes, the logical function they perform, and their inputs. Here's an example from the graphiit page:

```
from graphiit import Graph

graph_config = [
    ('A', 'OR', 'B', 'C'),
    ('B', 'AND', 'A', 'C'),
    ('C', 'XOR', 'A', 'B')]

graph = Graph(graph_config)

network = graph.pyphi_network()
```

Best,

Matteo

**Comment by yaacovNaNachRabbeinu** [comment]
Hello, u didn't quite understand, so suppose there are several ways. I understood that if I just create a tpm and connectivity matrix for `pyphi.Network()` I should then be able to use `network = graph.pyphi_network(tpm, cm=cm, node_labels=['A','B','C'])` as below, but I still get `got an unexpected keyword argument 'cm'`:

```

#python
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyphi
>>> 
>>> import numpy as np
>>> from graphiit import Graph
>>> graph_config = [
...     ('A', 'OR', 'B', 'C'),
...     ('B', 'AND', 'A', 'C'),
...     ('C', 'XOR', 'A', 'B')]
>>> graph = Graph(graph_config)
>>> network = graph.pyphi_network()
>>> tpm = np.array([
... [0.0, 0.0, 0.0],
... [0.0, 0.0, 1.0],
... [1.0, 0.0, 1.0],
... [1.0, 0.0, 0.0],
... [1.0, 0.0, 0.0],
... [1.0, 1.0, 1.0],
... [1.0, 0.0, 1.0],
... [1.0, 1.0, 0.0]
... ])
>>> cm = np.array([
... [0,1,1],
... [1,0,1],
... [1,1,0],
... ])
>>> network = graph.pyphi_network(tpm, cm=cm, node_labels=['A','B','C'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: pyphi_network() got an unexpected keyword argument 'cm'
>>> 

```
Another understanding of what you explained is that I should just do:

```
from graphiit import Graph

graph_config = [
    ('A', 'OR', 'B', 'C'),
    ('B', 'AND', 'A', 'C'),
    ('C', 'XOR', 'A', 'B')]

graph = Graph(graph_config)

network = graph.pyphi_network()
```
About the latter means that I should just do as below:

```
>>> tpm = np.array([
... [0.0, 0.0, 0.0],
... [0.0, 0.0, 1.0],
... [1.0, 0.0, 1.0],
... [1.0, 0.0, 0.0],
... [1.0, 0.0, 0.0],
... [1.0, 1.0, 1.0],
... [1.0, 0.0, 1.0],
... [1.0, 1.0, 0.0]
... ])
>>> cm = np.array([
... [0,1,1],
... [1,0,1],
... [1,1,0],
... ])
```
and will automatically be updated in `def pyphi_network(self)` from `graph.py`?
